### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [dmtsys/weblocaltime#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by davidhq** [comment]
Yes please, sure .... just send a pull request. Thank you!

**Comment by davidhq** [comment]
hi @geopic and @Vehmloewff 

as you can see, the library has been rewritten to typescript and `WebLocalTimeOptions` type exported

Thank you @Vehmloewff for a rewrite. 

I have commited a change now but would like to hear feedback from both of you, notable changes:

- do not export `localTime` function or `LocalTimeOptions` options anymore because all of this is returned as `parts` field of the main `weblocaltime` function and if anything, it might be confusing and also library is promoted as only providing **one function** (for simplicity)

- I exported `weblocaltime` function as default so it is possible to just do 

```js
import weblocaltime from 'weblocaltime';
```

or even something like this

```js
import localTime from 'weblocaltime';
```
<hr>

type can be imported like this in typescript (??)

```js
import { WebLocalTimeOptions } from 'weblocaltime';
```

I don't know almost anything about typescript yet, so I'm asking if these things make sense?

Can @geopic please test in practice if everything makes sense and that you can import the type as you wanted / needed?

also both please comment about your opinion on default export when the library is not planned to evolve further and always wants to provide just one simple function.

thank you

**Comment by geopic** [comment]
Cheers @Vehmloewff for the TS rewrite. 👍

@davidhq A single default export works just fine and is actually preferable in my view for a library which is non-modular like this one. The only case where I'd recommend exporting each function, class, object etc individually would be in the case of a large library containing many different items that achieve different purposes, such as `date-fns`. If this library is aiming to provide just one function for simplicity's sake then the default export is perfect for that.

Even then a TS developer is able to import non-default items as well, like so:
```js
import weblocaltime, { WebLocalTimeOptions } from 'weblocaltime';
```

**Comment by davidhq** [comment]
@geopic ok great, then this is agreed.

So you think the API is more or less good as it is? Does everything work in TS world? Editors etc?

**Comment by davidhq** [comment]
PS: I just found a comment from someone else (via reddit):


> I would recommend you opt in to stricter type checking, you can read about that here: > https://www.typescriptlang.org/tsconfig#Strict_Type_Checking_Options_6173

> This should really be the default but unfortunately it isn't for backwards compatibility reasons

Is there anything we can do about this ? Again, I'm not a TS person, not sure what he is saying

**Comment by geopic** [comment]
So the main purpose behind using TypeScript is to ensure that the types of data (`string`, `number`, `boolean` etc) passed in to functions as arguments are the type of data that is expected. This is to prevent bugs that arise from human error, like 'adding' numbers together which are actually strings so instead of `2 + 2 = 4` you're actually doing `"2" + "2" = "22"`, which leads to confusion.

The `strict` option in `tsconfig.json` is shorthand for a collection of options, all of which serve to further protect against unexpected behaviour. Looking at the file now I see @Vehmloewff added `noImplicitAny` (where you must state what type a value is if the TypeScript IDE extension / compiler cannot assume) and `noImplicitThis` (essentially the same, it requires that the structure of an object that `this` refers to must be known). They're both included in `strict`, so if you turn `strict` on you enable those as well as four other options, listed in this article: https://dev.to/briwa/how-strict-is-typescript-s-strict-mode-311a

The commentor's saying `strict` should be enabled by default because it should, lol. It is a big help because it provides structure and cohesion to a project. You just have to write directly what type a value is, what structure an object takes, and so on. It takes more time in the beginning but that time is taken out of the hours you'd spend debugging instead. It's up to you anyway man, but I would wholeheartedly recommend it.

**Comment by davidhq** [comment]
@geopic so if I understand correctly we can remove these two options and just make it `strict` ?

Would you mind doing this please? You can commit to the repo directly. 

It would be greatly appreciated.

**Comment by geopic** [comment]
Thanks, I appreciate the offer but it's not so hard to change, you just need to add `"strict": true` to the `tsconfig.json` file and remove `"noImplicitAny": true` and `"noImplicitThis": true` since they're part of the `strict` family of rules.

**Comment by Vehmloewff** [comment]
@davidhq, if it is ok with you, I can do the work to enable strict mode.

**Comment by davidhq** [comment]
> @davidhq, if it is ok with you, I can do the work to enable strict mode.

ok sure, yes please

**Comment by davidhq** [comment]
and nothing was done
